services:
  db:
    image: postgres:15-alpine
    container_name: velodrive-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: velodrive_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Password123
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: