spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/velodrive_db
    username: admin
    password: Password123
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
     group-id: velodrive-inventory-consumer-group